# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Get number of CPU cores
      uses: SimenB/github-actions-cpu-cores@v2
      id: cpu-cores

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build_arm64
      run: GOOS=linux GOARCH=arm64 CGO_ENABLES=0 go build -o result/Cloudreve_arm64 -ldflags "-s -w" -tags "go_json" -p ${{ steps.cpu-cores.outputs.count }} -a

    - name: Upload arm64
      uses: actions/upload-artifact@v4
      with:
          name: Cloudreve_arm64
          path: result/Cloudreve_arm64

    - name: Build_amd64
      run: CGO_ENABLES=0 GOOS=linux GOARCH=amd64 go build -o result/Cloudreve_amd64 -ldflags "-s -w" -tags "go_json" -p ${{ steps.cpu-cores.outputs.count }} -a

    - name: Upload amd64
      uses: actions/upload-artifact@v4
      with:
          name: Cloudreve_amd64
          path: result/Cloudreve_amd64
