name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16.20.2'
      - name: node
        run: cd assets
      - run: yarn install
      - run: yarn build
      - name: packaged
        run: cd build
      - run: find . -name "*.map" -type f -delete
      - run: cd ../../
      - run: zip -r - assets/build >assets.zip
      
